# Generated by Django 4.1.2 on 2022-11-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogpost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "pic1",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="uploads"
                    ),
                ),
                (
                    "pic2",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="uploads"
                    ),
                ),
                (
                    "maincategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.maincategory",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subcategory",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Buyer",),
        migrations.RemoveField(model_name="product", name="brand",),
        migrations.RemoveField(model_name="product", name="maincategory",),
        migrations.RemoveField(model_name="product", name="subcategory",),
        migrations.DeleteModel(name="Brand",),
        migrations.DeleteModel(name="Product",),
    ]
