# Generated by Django 4.1.2 on 2022-11-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_blogpost_delete_buyer_remove_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="pic1",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="uploads"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="pic2",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="uploads"
            ),
        ),
    ]
