# Generated by Django 4.1.2 on 2022-11-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_alter_blogpost_pic1_alter_blogpost_pic2"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="posturl",
            field=models.CharField(default="", max_length=55),
        ),
    ]
