# Generated by Django 4.1.2 on 2022-12-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_blogpost_paragraph1_blogpost_paragraph2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="captcha",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
