# Generated by Django 4.1.2 on 2022-12-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0007_contact_captcha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact", name="captcha", field=models.TextField(),
        ),
    ]
